### ISSUE TITLE
Thumnail Using remote URL

### ISSUE THREAD

**Issue by ak868308** [himiklab/yii2-easy-thumbnail-image-helper#10]
Hi
@himiklab thanks lot for such a wonderfull extension. It really helps and saves our time.
Here I would like to know how we can cache and thumbnail the image using remote URL.
When I followed the source code there is an alias used for source directory '@web/' but what about the third party URL. Suppose any image is stored on google drive and available with public URL, and the same wants to display here in my web using this extension then I can't do that! Because the code always looks file into '@web/'<rest path> 

Can you please help me with any additional function
Until then I will try my best with existing code :+1: 

Thanks

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-easy-thumbnail-image-helper/commit/1c3461d374b4a9b5debfa6a62604142e395404c3
