### ISSUE TITLE
Getting only the source Url where the cache image is stored.

### ISSUE THREAD

**Issue by adummy832** [himiklab/yii2-easy-thumbnail-image-helper#14]
Hi, @himiklab. First thank you for this plugin, This maybe an enhancement. Btw can you provide an API which only extracts the URL of  the cache image? Because I'm using a different tags not particularly an ```<img/>``` tag and I only want the URL of it. Thank you very much.

**Comment by himiklab** [comment]
Hello!
Try EasyThumbnailImage::thumbnailFileUrl.

**Comment by adummy832** [comment]
Hi @himiklab , just a question. Can i use .pdf files to generate a thumbnail?

**Comment by himiklab** [comment]
No.
