### ISSUE TITLE
v1.1.4 incorrect work with EasyThumbnailImage::THUMBNAIL_INSET parametr

### ISSUE THREAD

**Issue by bashcod** [himiklab/yii2-easy-thumbnail-image-helper#19]
Имеем изображение размерами, допустим 100*100px.
Пытаемся его вписать в рамки 50*100px.
Ожидаемый результат - получаем изображение на выходе размером 50*50px.
факт: получаем изображение размером 50*100px. Изображение вписано, сверху и снизу - залито пустотой.
`
echo EasyThumbnailImage::thumbnailImg(
    $model->pictureFile,
    50,
    50,
    EasyThumbnailImage::THUMBNAIL_INSET,
    ['alt' => $model->pictureName]
);
`
**Expect:** 
![default](https://user-images.githubusercontent.com/40749346/48290249-01208000-e494-11e8-9144-b16aa737bb32.png)

**Fact:** 
![default](https://user-images.githubusercontent.com/40749346/48290323-45138500-e494-11e8-94cc-df1c7b1df8fd.png)

**Comment by bashcod** [comment]
v1.1.3 Works correctly

**Comment by himiklab** [comment]
Поведение приведено к `yii\imagine\Image::thumbnail()` поставьте одному из измерений null или воспользуйтесь новым режимом https://github.com/himiklab/yii2-easy-thumbnail-image-helper/commit/3a08e8c22ca6ceaca21c1379879e7307ed801609

**Comment by bashcod** [comment]
спасибо!
