### ISSUE TITLE
Composer Installation Error

### ISSUE THREAD

**Issue by yiioverflow** [himiklab/yii2-easy-thumbnail-image-helper#2]
$ composer require "himiklab/yii2-easy-thumbnail-image-helper" : "*"                                                                                                                                     
  [InvalidArgumentException]                                                                                                         
  Could not find package * at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [packages1] ... [packagesN]

**Comment by himiklab** [comment]
Try add "himiklab/yii2-easy-thumbnail-image-helper": "*" in project`s composer.json file.
