### ISSUE TITLE
Alpha problem after creation of thumbnail

### ISSUE THREAD

**Issue by Sven-v-Beuningen** [himiklab/yii2-easy-thumbnail-image-helper#6]
Hi,

I have some transparent png images with transparent drop shadows. The images are optimised with pngquant and optipng to reduce the file size. The images do look fine with their original size, but after resizing with this extension the drop shadow border is not fading out any more. It is just a solid black border. Is there any kind of option which I can set to prevent this?

So long

Sven

**Comment by worstinme** [comment]
I had the same problem with \yii\imagine\Image.
The problem was solved after i'd updated php version (It may be the case in php libraries for images)

**Comment by Sven-v-Beuningen** [comment]
Hi Evgeny,

thank you for your response. That might be a solution. In Addition I found out, that this only happens for png's which are optimized with pngquant and optpng. Because optpng doesn't do much, I think it is pngquant.

So long,

Sven
