### ISSUE TITLE
Unsupported operand types

### ISSUE THREAD

**Issue by chrisb34** [himiklab/yii2-easy-thumbnail-image-helper#9]
I'm getting an error when trying to create a thumbnail 
Exception 'Imagine\Exception\RuntimeException' with message 'imagejpeg() expects parameter 3 to be long, array given' 
in .../vendor/imagine/imagine/lib/Imagine/Gd/Image.php:690

change line 99 of EasyThumbnailImage.php from
    $image->save($thumbnailFile, $options);
to 
    $image->save($thumbnailFile, $quality);

Thanks!

**Comment by himiklab** [comment]
Hello!
In Imagine 0.6.3:
`public function save($path = null, array $options = array());`
`$options` should be array
